name: Build HoloISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Git and archiso
        run: |
          sudo pacman -Sy --noconfirm git archiso

      - name: Build ISO
        run: |
          cd HoloISO-China
          mkarchiso -v .
          
      - name: Upload ISO
        uses: actions/upload-artifact@v3
        with:
          name: holoiso-iso
          path: HoloISO-China/out/*.iso
