name: Build HoloISO in Arch

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Update package database and install archiso
        run: pacman -Sy --noconfirm archiso

      - name: Clone HoloISO repository
        run: git clone https://github.com/bhaiest/holoiso/

      - name: Build HoloISO
        working-directory: holoiso
        run: mkarchiso -v holoiso
