name: Build HoloISO-China

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Install Git and archiso
        run: |
          pacman -Sy --noconfirm git archiso

      - name: Clone HoloISO-China repository
        run: git clone https://github.com/Gsjsjzhznsz/HoloISO-China.git

      - name: Build HoloISO
        run: |
          cd HoloISO-China  # 进入克隆的目录
          sudo mkarchiso -v .  # 使用当前目录作为参数
