name: Build HoloISO-China

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged  # 允许特权操作
    steps:
      - name: Install Git and archiso
        run: |
          pacman -Sy --noconfirm git archiso

      - name: Clone HoloISO-China repository
        run: git clone https://github.com/Gsjsjzhznsz/HoloISO-China.git

      - name: Update pacman mirrors
        run: |
          echo 'Server = https://mirrors.kernel.org/archlinux/$repo/os/$arch' > /etc/pacman.d/mirrorlist
          pacman -Sy

      - name: Build HoloISO
        run: |
          cd HoloISO-China  # 进入克隆的目录
          mkarchiso -v .  # 直接运行 mkarchiso，不使用 sudo
